### ISSUE TITLE
How can I use the package? 

### ISSUE THREAD

**Issue by tobias96** [hbatalhaStch/react-big-scheduler#1]
I have installed the fork with `npm install https://github.com/hbatalhaStch/react-big-scheduler --save`. 

But that does not seem to be enough. After that I always get the following error: `TS2307: Cannot find module 'react-big-scheduler-stch' or its corresponding type declarations.`

**Comment by hbatalhaStch** [comment]
Sorry for the late reply I thought I was watching this repository but turns out I wasn't , so I didn't receive notification about this issue.

> **How can I use the package?**

I haven't published it yet because I still have some bugs I need to fix before.

**Comment by hbatalhaStch** [comment]
I plan on publishing the fork tomorrow, the package is going to be named `react-big-scheduler-stch`

**Comment by hbatalhaStch** [comment]
@tobias96 I have publish it: https://www.npmjs.com/package/react-big-scheduler-stch
