### ISSUE TITLE
Use of script file

### ISSUE THREAD

**Issue by ansulagrawal** [hbatalhaStch/react-big-scheduler#14]
### Checklist

- [X] I've looked through the [README](https://github.com/hbatalhaStch/react-big-scheduler#readme)
- [X] I've verified that I'm running react-big-scheduler-stch version **1.3.0**

### Please make sure the question is worded well enough to be understood

I want to know what the use of all below script is:

- `clean:exampledist`
- `build:exampledist`
- `analyz`
- `build:dll`

**Comment by hbatalhaStch** [comment]
I haven't yet had the need to use them so I can't give you a concrete answer as of now.
