### ISSUE TITLE
Editing "weekend" cells that render with a red/pink background

### ISSUE THREAD

**Issue by fabiansvensson** [hbatalhaStch/react-big-scheduler#19]
### Checklist

- [X] I've looked through the [README](https://github.com/hbatalhaStch/react-big-scheduler#readme)
- [X] I've verified that I'm running react-big-scheduler-stch version **1.3.0**

### Please make sure the question is worded well enough to be understood

I noticed every 6th and 7th days (representing weekends) get a red/pink background and grey text. I would want to display these differently.

I found that we can edit the header using nonAgendaCellHeaderTemplateResolver, however, I cannot figure out how to edit the regular cells.

Here you can see an example of what I am referring to (notice columns 6/3, 6/4, 6/10 and 6/11):
<img width="1007" alt="before" src="https://github.com/hbatalhaStch/react-big-scheduler/assets/19996004/6d415fa3-cff7-47f0-a46a-0ebcbfbe0d62">

**Comment by hbatalhaStch** [comment]
you can edit those cells by setting the SchedulerData config [nonWorkingTimeBodyBgColor](https://github.com/hbatalhaStch/react-big-scheduler#nonworkingtimebodybgcolor)
```ts
new SchedulerData('2023-04-18', ViewType.Month, false, false,
    { 
        nonWorkingTimeBodyBgColor: 'green',
    });
```

**Comment by fabiansvensson** [comment]
@hbatalhaStch Sorry for the late reply. 

Thank you very much for the solution, that works :)

**Comment by hbatalhaStch** [comment]
@fabiansvensson you are welcome!
