### ISSUE TITLE
Custom display of empty cells

### ISSUE THREAD

**Issue by RobinMillian** [hbatalhaStch/react-big-scheduler#2]
Hello,

I'm looking to create custom elements or putting css depending on the day for each empty cell

After hours of digging in the library code I can see how the empty cells are rendered (in the BodyView.js file) but despite regular cells being customizable it looks like the empty cells cannot be.

Is this feature scheduled any time soon ? If not, would you accept a PR for this change ?

UPDATE
It looks like the code can actually allow for some kind of customization, but that it's actually the associated typing that might not be up to date ?
In BodyViews, there is 
```
if (!!behaviors.getNonAgendaViewBodyCellBgColorFunc) {
                        var cellBgColor = behaviors.getNonAgendaViewBodyCellBgColorFunc(schedulerData, item.slotId, header);
                        if (!!cellBgColor) style = _extends({}, style, { backgroundColor: cellBgColor });
                    }
```
But the associating typing for "behaviors" doesn't have `getNonAgendaViewBodyCellBgColorFunc` in it's typing.

**Comment by hbatalhaStch** [comment]
> But the associating typing for "behaviors" doesn't have getNonAgendaViewBodyCellBgColorFunc in it's typing.

Yeah you are right. Thank you for noticing, I have updated the typings.

>I'm looking to create custom elements or putting css depending on the day for each empty cell

If I am understanding it correctly you want to be able to customize specific days in the scheduler either by modifying its css and adding an element, right?
It would be of great help if you could show me how the api would look like.

>Is this feature scheduled any time soon ? If not, would you accept a PR for this change ?

I can look into it but if you figure it out you can create a PR, it would be appreciated.
