### ISSUE TITLE
I need help for the question that is been asked in my repo can you please help becasuse I tried all possible ways

### ISSUE THREAD

**Issue by ansulagrawal** [hbatalhaStch/react-big-scheduler#20]
@hbatalhaStch sorry this question is not from your repo but can you help me by answering different user for my repo that code is fork from your repo so.

issue: 
https://github.com/react-scheduler/react-big-schedule/issues/60

**Comment by hbatalhaStch** [comment]
@ansulagrawal I am sorry for the late reply.
Is my help still needed?

**Comment by ansulagrawal** [comment]
Yes please

**Comment by ansulagrawal** [comment]
@hbatalhaStch did you find the answer?
if not I will close this issue.

**Comment by hbatalhaStch** [comment]
@ansulagrawal sorry for the late replies, I haven't been getting much free time lately.

I will take a look but it would be better if another issue was created to address that problem.as it is different from the one mentioned in the thread title

**Comment by ansulagrawal** [comment]
Ok will ask him to create it or I will create a new issue with it.
