### ISSUE TITLE
Scheduler Hover Bug

### ISSUE THREAD

**Issue by SyedNaqeebUlHassan** [hbatalhaStch/react-big-scheduler#21]
### Checklist

- [ ] I've verified that I'm running react-big-scheduler-stch version **1.3.0**

### Describe the bug

Hy, i am currently facing an issue regarding to hover effect on scheduler. Hover model is going out of position. I will share screenshots so you will understand better.

![image](https://github.com/hbatalhaStch/react-big-scheduler/assets/102452693/e27d6956-51ff-4a8b-97db-4fb8ede347f5)

Please notice on position of hover model.When I scroll my calendar the position of hover model remain stick,that cause him to go outside of view.

Screenshot after scroll:

![image](https://github.com/hbatalhaStch/react-big-scheduler/assets/102452693/09afd19c-92c9-45c7-a28d-5ba160db44c9)

So you see, model is going out of window.

I am using react-big-scheduler-stch version 1.1.1

Please response me back if you already solved this,if not I will solve this and will create pull request.

Thanks,

Developer from Daum Solutions.

### Reproduction Link/Code

I think problem is inside table element. In table element there is a position absolute assign somewhere which is causing a problem. 

### Steps to reproduce

1.Table Element of id="RBS-scheduler-root" class="scheduler"

**Comment by hbatalhaStch** [comment]
You can use SchedulerData.config  [~eventItemPopoverWidth~ eventItemPopoverPlacement](https://github.com/hbatalhaStch/react-big-scheduler#eventitempopoverplacement) mousePosition variants (`'topLeftMousePosition' | 'bottomLeftMousePosition' | 'topRightMousePosition' | 'bottomRightMousePosition'`)

**Comment by SyedNaqeebUlHassan** [comment]
I am not able to find config property.This is my code,please guide me.

  let schedulerData = new SchedulerData(
    date,
    ViewType.Day, 
    false,
    false,
    {

    },
  );
  
  I am not able to find that option
  
  
![image](https://github.com/hbatalhaStch/react-big-scheduler/assets/102452693/fcdd3753-bf51-4d27-8a7e-af5ccedd8d27)

Can you please provide me some example?

**Comment by hbatalhaStch** [comment]
I apologize I wrote the wrong config. It's `eventItemPopoverPlacement`, not `eventItemPopoverWidth`.

```ts
let schedulerData = new SchedulerData(date,
    ViewType.Day,
    false,
    false,
    {
         // choose one
        // eventItemPopoverPlacement: 'topLeftMousePosition'
        // eventItemPopoverPlacement: 'topRightMousePosition'
        // eventItemPopoverPlacement: 'bottomLeftMousePosition'
        eventItemPopoverPlacement: 'bottomRightMousePosition'
    }
);
```

**Comment by SyedNaqeebUlHassan** [comment]
Another Problem I found is:

![image](https://github.com/hbatalhaStch/react-big-scheduler/assets/102452693/2a7d1b61-6730-4e4e-b172-0c55e7036b08)

The week should be stretch to full width, do you have any idea how to do it?

**Comment by SyedNaqeebUlHassan** [comment]
I found another bug.

![image](https://github.com/hbatalhaStch/react-big-scheduler/assets/102452693/cc1fe214-51e2-476f-8577-a22eeebd2921)

The week day should be stretch to full width. Do you have any idea how to solve this problem.

**Comment by hbatalhaStch** [comment]
Please create a new issue for this bug and provide more details like code and how to reproduce it and close this issue if it is complete.
