### ISSUE TITLE
Convert Project to Organization

### ISSUE THREAD

**Issue by ansulagrawal** [hbatalhaStch/react-big-scheduler#23]
Hi @hbatalhaStch, need to know your intrest to convert this project to a new organization. You can be owner and I will remove my project also. This will be better for us to handle and make it more better way to organize it.

I need you suggestions on this.

**Comment by hbatalhaStch** [comment]
Yes I am interested.
We should have a meeting to better talk about this.

**Comment by ansulagrawal** [comment]
yes sure you can sechedule a meeting on Monday to Friday after 5:30pm IST or Saturday and Sunday after 11:00 AM IST

Here is my mail: ansulagrawal9@gmail.com
