### ISSUE TITLE
withDnDContext issue of wrapping when using react-dnd and react-dnd-html5-backend at 16.0.1

### ISSUE THREAD

**Issue by AsifDaum** [hbatalhaStch/react-big-scheduler#4]
To resolve this I had to downgrade my react-dnd and the html5-backend to the one stated in the package (14.0.5 and 14.0.1), I have not investigated why in depth or any other versions, but if you come across this issue you will have to downgrade this.

**Comment by hbatalhaStch** [comment]
The reason why you had to downgrade to those versions is because those are the last versions that react-dnd uses `DragSource` and `DragTarget`, now they use hooks (`useDrag` and `useDrop` respectively) which can't be used in class components.
